### ISSUE TITLE
karma init error on windows

### ISSUE THREAD

**Issue by eikooc** [karma-runner/karma-cli#18]
Got this error when running `karma init`
Karma cli version 0.13.16
Clean install of node with jasmine and karma npm packages

```
readline.js:525
  this.line = this.line.slice(this.cursor);
                       ^

TypeError: Cannot read property 'slice' of undefined
    at Interface._deleteLineLeft (readline.js:525:24)
    at suggestNextOption (C:\project\node_modules\karma\lib\init\state_machine.js:43:9)
    at nextQuestion (C:\project\node_modules\karma\lib\init\state_machine.js:119:12)
    at process (C:\project\node_modules\karma\lib\init\state_machine.js:135:10)
    at Object.exports.init (C:\project\node_modules\karma\lib\init.js:247:6)
    at Object.exports.run (C:\project\node_modules\karma\lib\cli.js:237:25)
    at requireCliAndRun (C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\bin\karma:44:16)
    at C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\bin\karma:54:12
    at C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\node_modules\resolve\lib\async.js:44:21
    at ondir (C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\node_modules\resolve\lib\async.js:187:31)
    at C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\node_modules\resolve\lib\async.js:153:39
    at onex (C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\node_modules\resolve\lib\async.js:93:22)
    at C:\Users\user\AppData\Roaming\nvm\v5.3.0\node_modules\karma-cli\node_modules\resolve\lib\async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by Prophet32j** [comment]
+1
Same thing for me. This also was happening when executing karma from node_modules.

**Comment by Doormouse2House** [comment]
+1

**Comment by warapitiya** [comment]
Even the windows command line not working for me. :-1:

**Comment by malkomich** [comment]
Yes, as @Doormouse2House said it works fine in Windows CLI.

Probably you're using the Git Bash terminal, MinTTY, which doesn't have full support for TTY.

You have 4 options to fix the problem:

1. Use CMD terminal with the **Windows shell** (the default Windows console)
2. Use CMD terminal with the **Bash shell** (execute `"C:\Program Files\Git\bin\bash.exe" --login -i` in cmd terminal)
3. Use Powershell (an alternative terminal typically installed by default in Windows environments)
4. Use an alternative terminal (or develop a new one :stuck_out_tongue_winking_eye: )

If you just need execute isolated interactive commands like `karma init`, I recommend **option 1** for it and then come back to Git Bash. However I would give a try to Powershell.

**Comment by chidimo** [comment]
Same problem here. I have tried everything stated above. I even issue `karma` command from within `node_modules/karma/bin` folder.

Its not working
