### ISSUE TITLE
Problem with `npm install karma-cli` after running `npm install karma`

### ISSUE THREAD

**Issue by tjanez** [karma-runner/karma-cli#9]
I encountered a problem re-running `npm install karma-cli` after running `npm install karma-cli`.

The system is an up2date Debian Wheezy with `npm` from Node.js apt repository.

Here the steps to reproduce the problem:

```
root@gentest:/home/genialis# npm -v
1.4.28
root@gentest:/home/genialis# npm list
/home/genialis
└── (empty)

root@gentest:/home/genialis# npm install karma-cli
karma-cli@0.0.4 node_modules/karma-cli
└── resolve@0.5.1
root@gentest:/home/genialis# npm install karma
npm WARN optional dep failed, continuing fsevents@0.3.6
/
> ws@0.4.32 install /home/genialis/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/genialis/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/genialis/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
karma@0.12.36 node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.0
├── q@1.4.1
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── useragent@2.1.6 (lru-cache@2.2.4)
├── source-map@0.4.2 (amdefine@0.1.0)
├── chokidar@1.0.3 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, path-is-absolute@1.0.0, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── log4js@0.6.25 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── connect@2.29.2 (utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.2.4, cookie@0.1.2, pause@0.0.1, response-time@2.3.1, vhost@3.0.0, content-type@1.0.1, basic-auth-connect@1.0.0, on-headers@1.0.0, bytes@1.0.0, parseurl@1.3.0, depd@1.0.1, cookie-parser@1.3.5, http-errors@1.3.1, connect-timeout@1.6.2, method-override@2.3.3, qs@2.4.2, finalhandler@0.3.6, morgan@1.5.3, debug@2.2.0, express-session@1.10.4, csurf@1.7.0, type-is@1.6.2, serve-favicon@2.2.1, multiparty@3.3.2, serve-static@1.9.3, body-parser@1.12.4, errorhandler@1.3.6, compression@1.4.4, serve-index@1.6.4)
├── lodash@3.9.3
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
root@gentest:/home/genialis# npm install karma-cli
npm ERR! Refusing to delete: /home/genialis/node_modules/.bin/karma not in /home/genialis/node_modules/karma-cli
File exists: /home/genialis/node_modules/.bin/karma
Move it away, and try again. 

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "karma-cli"
npm ERR! cwd /home/genialis
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/genialis/node_modules/.bin/karma
npm ERR! code EEXIST
npm ERR! error rolling back Error: Refusing to delete: /home/genialis/node_modules/.bin/karma not in /home/genialis/node_modules/karma-cli
npm ERR! error rolling back     at clobberFail (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! error rolling back  { [Error: Refusing to delete: /home/genialis/node_modules/.bin/karma not in /home/genialis/node_modules/karma-cli]
npm ERR! error rolling back   code: 'EEXIST',
npm ERR! error rolling back   path: '/home/genialis/node_modules/.bin/karma' }
npm ERR! not ok code 0
root@gentest:/home/genialis#
```

**Comment by Dignifiedquire** [comment]
You should not be installing `karma-cli` into a local module, because `karma` does provide a `bin` link on its own locally. Rather `karma-cli` is thought of being installed as globally by running `npm install -g karma-cli` so that it lands in your path. It then detects local installations and uses them if you go into a directory to run `karma`.

**Comment by tjanez** [comment]
@Dignifiedquire, thanks for your tip.

Unfortunately, it doesn't solve the problem. The same thing happens if I install the modules globally (with `-g` argument).

Here are the steps to reproduce the problem:
```
root@gendev:/home/genialis# npm -v
1.4.28
root@gendev:/home/genialis# npm -g list
/usr/lib
└─┬ npm@1.4.28
  ├── abbrev@1.0.5
  ├── ansi@0.3.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── archy@0.0.2
  ├── block-stream@0.0.7
  ├── char-spinner@1.0.1
  ├── child-process-close@0.1.1
  ├── chmodr@0.1.0
  ├── chownr@0.0.1
  ├── cmd-shim@2.0.0 (git://github.com/othiym23/cmd-shim#12de64ca97f45ac600910092f19afacc3d5376dd)
  ├─┬ columnify@1.2.1
  │ ├─┬ strip-ansi@1.0.0
  │ │ └── ansi-regex@0.2.1
  │ └─┬ wcwidth@1.0.0
  │   └─┬ defaults@1.0.0
  │     └── clone@0.1.18
  ├── editor@0.1.0
  ├── fstream@1.0.2
  ├─┬ fstream-npm@1.0.0
  │ └── fstream-ignore@1.0.1
  ├── github-url-from-git@1.4.0
  ├── github-url-from-username-repo@1.0.0
  ├── glob@4.0.5
  ├── graceful-fs@3.0.2
  ├── inflight@1.0.1
  ├── inherits@2.0.1
  ├── ini@1.2.1
  ├─┬ init-package-json@1.0.0
  │ └── promzard@0.2.2
  ├── lockfile@1.0.0
  ├── lru-cache@2.5.0
  ├─┬ minimatch@1.0.0
  │ └── sigmund@1.0.0
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  ├── node-gyp@1.0.1
  ├── nopt@3.0.1
  ├── npm-cache-filename@1.0.1
  ├── npm-install-checks@1.0.2
  ├── npm-registry-client@2.0.7
  ├── npm-user-validate@0.1.0
  ├─┬ npmconf@1.1.8
  │ └─┬ config-chain@1.1.8
  │   └── proto-list@1.2.3
  ├── npmlog@0.1.1
  ├── once@1.3.0
  ├── opener@1.3.0
  ├── osenv@0.1.0
  ├── path-is-inside@1.0.1
  ├─┬ read@1.0.5
  │ └── mute-stream@0.0.4
  ├─┬ read-installed@2.0.5
  │ └── util-extend@1.0.1
  ├─┬ read-package-json@1.2.7
  │ └── normalize-package-data@1.0.1
  ├─┬ request@2.42.0
  │ ├── aws-sign2@0.5.0
  │ ├─┬ bl@0.9.1
  │ │ └─┬ readable-stream@1.0.31
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├── caseless@0.6.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.1.4
  │ │ ├── async@0.9.0
  │ │ ├─┬ combined-stream@0.0.5
  │ │ │ └── delayed-stream@0.0.5
  │ │ └── mime@1.2.11
  │ ├─┬ hawk@1.1.1
  │ │ ├── boom@0.4.2
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.9.1
  │ │ └── sntp@0.2.4
  │ ├─┬ http-signature@0.10.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.2
  │ │ └── ctype@0.5.2
  │ ├── json-stringify-safe@5.0.0
  │ ├── mime-types@1.0.2
  │ ├── node-uuid@1.4.1
  │ ├── oauth-sign@0.4.0
  │ ├── qs@1.2.2
  │ ├── stringstream@0.0.4
  │ ├─┬ tough-cookie@0.12.1
  │ │ └── punycode@1.3.1
  │ └── tunnel-agent@0.4.0
  ├── retry@0.6.0
  ├── rimraf@2.2.8
  ├── semver@2.3.0
  ├─┬ sha@1.2.4
  │ └─┬ readable-stream@1.0.27-1
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.25-1
  ├── slide@1.1.6
  ├── sorted-object@1.0.0
  ├── tar@1.0.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.5
  └── which@1.0.5

root@gendev:/home/genialis# npm -g install karma-cli
/usr/bin/karma -> /usr/lib/node_modules/karma-cli/bin/karma
karma-cli@0.0.4 /usr/lib/node_modules/karma-cli
└── resolve@0.5.1
root@gendev:/home/genialis# npm -g install karma
npm WARN optional dep failed, continuing fsevents@0.3.6
\
> ws@0.4.32 install /usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
/usr/bin/karma -> /usr/lib/node_modules/karma/bin/karma
karma@0.12.36 /usr/lib/node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.0
├── q@1.4.1
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── useragent@2.1.6 (lru-cache@2.2.4)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── source-map@0.4.2 (amdefine@0.1.1)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── chokidar@1.0.3 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, path-is-absolute@1.0.0, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── lodash@3.9.3
├── connect@2.29.2 (utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.2, fresh@0.2.4, pause@0.0.1, response-time@2.3.1, vhost@3.0.0, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, bytes@1.0.0, parseurl@1.3.0, depd@1.0.1, qs@2.4.2, cookie-parser@1.3.5, http-errors@1.3.1, connect-timeout@1.6.2, method-override@2.3.3, debug@2.2.0, morgan@1.5.3, finalhandler@0.3.6, express-session@1.10.4, csurf@1.7.0, serve-favicon@2.2.1, multiparty@3.3.2, type-is@1.6.3, serve-static@1.9.3, body-parser@1.12.4, errorhandler@1.3.6, compression@1.4.4, serve-index@1.6.4)
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
root@gendev:/home/genialis# npm -g install karma-cli
npm ERR! Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli
File exists: /usr/bin/karma
Move it away, and try again. 

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "karma-cli"
npm ERR! cwd /home/genialis
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /usr/bin/karma
npm ERR! code EEXIST
npm ERR! error rolling back Error: Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli
npm ERR! error rolling back     at clobberFail (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! error rolling back  { [Error: Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli] code: 'EEXIST', path: '/usr/bin/karma' }
npm ERR! not ok code 0
root@gendev:/home/genialis#
```

Any ideas why this is happening?

**Comment by tjanez** [comment]
*Update*: I've just found a simpler reproducer.

You no longer need to run `npm -g install karma-cli` before running `npm -g install karma`. Just run `npm -g install karma`, followed by `npm -g install karma-cli`:
```
root@gendev:/home/genialis# npm -v
1.4.28
root@gendev:/home/genialis# npm -g list
/usr/lib
└─┬ npm@1.4.28
  ├── abbrev@1.0.5
  ├── ansi@0.3.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── archy@0.0.2
  ├── block-stream@0.0.7
  ├── char-spinner@1.0.1
  ├── child-process-close@0.1.1
  ├── chmodr@0.1.0
  ├── chownr@0.0.1
  ├── cmd-shim@2.0.0 (git://github.com/othiym23/cmd-shim#12de64ca97f45ac600910092f19afacc3d5376dd)
  ├─┬ columnify@1.2.1
  │ ├─┬ strip-ansi@1.0.0
  │ │ └── ansi-regex@0.2.1
  │ └─┬ wcwidth@1.0.0
  │   └─┬ defaults@1.0.0
  │     └── clone@0.1.18
  ├── editor@0.1.0
  ├── fstream@1.0.2
  ├─┬ fstream-npm@1.0.0
  │ └── fstream-ignore@1.0.1
  ├── github-url-from-git@1.4.0
  ├── github-url-from-username-repo@1.0.0
  ├── glob@4.0.5
  ├── graceful-fs@3.0.2
  ├── inflight@1.0.1
  ├── inherits@2.0.1
  ├── ini@1.2.1
  ├─┬ init-package-json@1.0.0
  │ └── promzard@0.2.2
  ├── lockfile@1.0.0
  ├── lru-cache@2.5.0
  ├─┬ minimatch@1.0.0
  │ └── sigmund@1.0.0
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  ├── node-gyp@1.0.1
  ├── nopt@3.0.1
  ├── npm-cache-filename@1.0.1
  ├── npm-install-checks@1.0.2
  ├── npm-registry-client@2.0.7
  ├── npm-user-validate@0.1.0
  ├─┬ npmconf@1.1.8
  │ └─┬ config-chain@1.1.8
  │   └── proto-list@1.2.3
  ├── npmlog@0.1.1
  ├── once@1.3.0
  ├── opener@1.3.0
  ├── osenv@0.1.0
  ├── path-is-inside@1.0.1
  ├─┬ read@1.0.5
  │ └── mute-stream@0.0.4
  ├─┬ read-installed@2.0.5
  │ └── util-extend@1.0.1
  ├─┬ read-package-json@1.2.7
  │ └── normalize-package-data@1.0.1
  ├─┬ request@2.42.0
  │ ├── aws-sign2@0.5.0
  │ ├─┬ bl@0.9.1
  │ │ └─┬ readable-stream@1.0.31
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├── caseless@0.6.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.1.4
  │ │ ├── async@0.9.0
  │ │ ├─┬ combined-stream@0.0.5
  │ │ │ └── delayed-stream@0.0.5
  │ │ └── mime@1.2.11
  │ ├─┬ hawk@1.1.1
  │ │ ├── boom@0.4.2
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.9.1
  │ │ └── sntp@0.2.4
  │ ├─┬ http-signature@0.10.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.2
  │ │ └── ctype@0.5.2
  │ ├── json-stringify-safe@5.0.0
  │ ├── mime-types@1.0.2
  │ ├── node-uuid@1.4.1
  │ ├── oauth-sign@0.4.0
  │ ├── qs@1.2.2
  │ ├── stringstream@0.0.4
  │ ├─┬ tough-cookie@0.12.1
  │ │ └── punycode@1.3.1
  │ └── tunnel-agent@0.4.0
  ├── retry@0.6.0
  ├── rimraf@2.2.8
  ├── semver@2.3.0
  ├─┬ sha@1.2.4
  │ └─┬ readable-stream@1.0.27-1
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.25-1
  ├── slide@1.1.6
  ├── sorted-object@1.0.0
  ├── tar@1.0.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.5
  └── which@1.0.5

root@gendev:/home/genialis# npm -g install karma
npm WARN optional dep failed, continuing fsevents@0.3.6
 
> ws@0.4.32 install /usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
/usr/bin/karma -> /usr/lib/node_modules/karma/bin/karma
karma@0.12.36 /usr/lib/node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.0
├── q@1.4.1
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── useragent@2.1.6 (lru-cache@2.2.4)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── source-map@0.4.2 (amdefine@0.1.1)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── chokidar@1.0.3 (path-is-absolute@1.0.0, arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── connect@2.29.2 (utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.2, fresh@0.2.4, pause@0.0.1, response-time@2.3.1, vhost@3.0.0, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, bytes@1.0.0, parseurl@1.3.0, depd@1.0.1, qs@2.4.2, cookie-parser@1.3.5, http-errors@1.3.1, connect-timeout@1.6.2, method-override@2.3.3, debug@2.2.0, finalhandler@0.3.6, morgan@1.5.3, express-session@1.10.4, csurf@1.7.0, serve-favicon@2.2.1, type-is@1.6.3, multiparty@3.3.2, serve-static@1.9.3, body-parser@1.12.4, errorhandler@1.3.6, compression@1.4.4, serve-index@1.6.4)
├── lodash@3.9.3
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
root@gendev:/home/genialis# npm -g install karma-cli
npm ERR! Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli
File exists: /usr/bin/karma
Move it away, and try again. 

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "karma-cli"
npm ERR! cwd /home/genialis
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /usr/bin/karma
npm ERR! code EEXIST
npm ERR! error rolling back Error: Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli
npm ERR! error rolling back     at clobberFail (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! error rolling back  { [Error: Refusing to delete: /usr/bin/karma not in /usr/lib/node_modules/karma-cli] code: 'EEXIST', path: '/usr/bin/karma' }
npm ERR! not ok code 0
root@gendev:/home/genialis#
```

**Comment by oratthumzap** [comment]
i'm also experiencing this issue and cannot get my build to pass :/

is there any workaround for this issue?

**Comment by Dignifiedquire** [comment]
You could workaround maybe by removing the bin file npm is complaining about manually. But for a full fix I see only two solutions, either drop `karma-cli` completely and let everyone install `karma` globally, or we have to remove the `bin` specification in the package.json of karma again.

//cc @karma-runner/contributors need some input from you on this please.

**Comment by oratthumzap** [comment]
we found a workaround -
install karma-cli as sudo
all other dependencies (karma, etc.) can be installed using the local user credentials

from our shippable.yml (continuous integration solution):
install:
    - npm install
    - shippable_retry "npm list -g --depth=0 | grep karma-cli || sudo npm install -g karma-cli"


our package.json:
{
  "name": "XXX-XXXX-XXX",
  "version": "0.0.0",
  "scripts": {
    "test": "karma start spec/karma.config.js --single-run"
  },
  "devDependencies": {  
    "karma": "*",
    "karma-jasmine": "*",
    "karma-phantomjs-launcher": "*",
    "karma-junit-reporter": "*",
    "karma-htmlfile-reporter": "*",
    "karma-coverage": "*",
    "karma-jasmine-jquery" : "*"

  },
  "private": true
}

**Comment by tjanez** [comment]
@Dignifiedquire,

any progress on this?

**Comment by rogeriopvl** [comment]
Is this still an issue? If not, I'm closing it in a couple of days.

**Comment by rogeriopvl** [comment]
Closing due to inactivity.

**Comment by ajithk444** [comment]
Getting this issue now when deploying to Azure using Kuduscript. Anyone getting this issue yet?

**Comment by rogeriopvl** [comment]
@ajithk444 can you provide some logs?

**Comment by qpooqp** [comment]
Hello

I have same issue. 

Scenario:
First i install **karma** globally (npm install -g karma) without problems.
Then, when i want to install **karma-cli** globally (npm install -g karma-cli), i'm getting error.

_npm ERR! code EEXIST
npm ERR! path C:\Users\jvavra\AppData\Roaming\npm\node_modules\karma-cli\bin\karma
npm ERR! dest C:\Users\jvavra\AppData\Roaming\npm\karma
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\jvavra\AppData\Roaming\npm\node_modules\karma-cli\bin\karma' -> 'C:\Users\jvavra\AppData\Roaming\npm\karma'
npm ERR! File exists: C:\Users\jvavra\AppData\Roaming\npm\karma
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly._

[full log of karma-cli install](https://github.com/karma-runner/karma-cli/files/4122624/2020-01-28T13_31_07_166Z-debug.log)

When i try to install it in different order (first karma-cli, then karma), then it behaves the same (error when installing the second thing - karma).

Any idea what is wrong?
